version: "3.7"
services:
  app:
    build:
      context: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/usr/src/app
      - gems:/usr/local/bundle
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:11.10-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  gems:
  pg-data: