default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: dns_storage_development

test:
  <<: *default
  database: dns_storage_test
